"""Initial conditions

Revision ID: e2915af027bf
Revises: 
Create Date: 2024-10-28 21:01:26.097642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2915af027bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_utc',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('from_user', sa.BigInteger(), nullable=False),
    sa.Column('forward_from_message_id', sa.BigInteger(), nullable=False),
    sa.Column('forward_from', sa.BigInteger(), nullable=False),
    sa.Column('forward_from_chat', sa.BigInteger(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('sticker_set_name', sa.Text(), nullable=False),
    sa.Column('new_chat_title', sa.Text(), nullable=False),
    sa.Column('reply_to_message', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('text_index_col', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(text, ''))", ), nullable=False)
    )
    op.create_index('messages_utc_date_index', 'messages_utc', ['date'], unique=False)
    op.create_index('messages_utc_from_user_index', 'messages_utc', ['from_user'], unique=False)
    op.create_index('messages_utc_type_index', 'messages_utc', ['type'], unique=False)
    op.create_index('text_idx', 'messages_utc', ['text_index_col'], unique=False, postgres_using='gin')
    op.create_table('user_events',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False)
    )
    op.create_index('ix_user_events_message_id', 'user_events', ['message_id'], unique=False)
    op.create_table('user_names',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False)
    )
    op.create_index('user_names_user_id_date_index', 'user_names', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_names_user_id_date_index', table_name='user_names')
    op.drop_table('user_names')
    op.drop_index('ix_user_events_message_id', table_name='user_events')
    op.drop_table('user_events')
    op.drop_index('text_idx', table_name='messages_utc', postgres_using='gin')
    op.drop_index('messages_utc_type_index', table_name='messages_utc')
    op.drop_index('messages_utc_from_user_index', table_name='messages_utc')
    op.drop_index('messages_utc_date_index', table_name='messages_utc')
    op.drop_table('messages_utc')
    # ### end Alembic commands ###
